name: Bug Report
description: File a bug report.
title: "[Bug]: "
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        This issue form is for reporting bugs only!
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version of Stirling-PDF
      placeholder: 0.0.2
      description: What version of Stirling-PDF has the issue?
  - type: input
    attributes:
      label: What was the last working version of Stirling-PDF?
      placeholder: 0.0.1
      description: >
        If known, otherwise leave blank.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: >
        If known, otherwise leave blank.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: No duplicate of the issue
      description: There is no issue with the same problem?
      options:
        - label: I have verified that there are no issues related to my problem.
          required: true
