name: A Self-Hosted

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted  // local windows runner

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧱 Gradle Build
        run: ./gradlew clean build
        shell: pwsh
        working-directory: ${{ github.workspace }}

      - name: 🛠️ Build Stirling-PDF Docker Image
        working-directory: ${{ github.workspace }}
        run: |
          docker build -t stirling-pdf-pr:latest .

      - name: 🧹 Stop and Remove if container exists
        shell: pwsh
        run: |
          $exists = docker ps -a --format '{{.Names}}' | Where-Object { $_ -eq 'stirling-pdf-pr' }
          if ($exists) {
              docker stop stirling-pdf-pr | Out-Null
              docker rm stirling-pdf-pr | Out-Null
          } else {
              Write-Host "Container stirling-pdf-pr does not exist, nothing to stop/remove."
          }

      - name: 🚀 Run Stirling-PDF Container
        working-directory: ${{ github.workspace }}
        run: |
          docker run -d `
            --name stirling-pdf-pr `
            -p 7777:8080 `
            -v /stirling/test/data:/usr/share/tessdata:rw `
            -v /stirling/test/config:/configs:rw `
            -v /stirling/test/logs:/logs:rw `
            -e DOCKER_ENABLE_SECURITY=true `
            -e SECURITY_ENABLELOGIN=true `
            -e SYSTEM_DEFAULTLOCALE=en-GB `
            -e UI_APPNAME="Stirling-PDF PR#manual" `
            -e UI_HOMEDESCRIPTION="Manual Test Deployment for Stirling-PDF" `
            -e UI_APPNAMENAVBAR="PR#manual" `
            -e SYSTEM_MAXFILESIZE=100 `
            -e METRICS_ENABLED=true `
            -e SYSTEM_GOOGLEVISIBILITY=false `
            --restart on-failure:5 `
            stirling-pdf-pr:latest
