name: a_Validate_PR_Changes

on:
  pull_request_target:
    paths:
      - "src/main/resources/messages_*.properties"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch PR changed files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching changed files using GitHub CLI..."
          gh pr view ${{ github.event.pull_request.number }} --json files -q ".files[].path" > changed_files.txt
          cat changed_files.txt
