name: AI Title Suggestion Request

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches: [main]

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      pr_number: ${{ steps.meta.outputs.pr_number }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v4

      - name: Extract PR metadata
        run: |
          mkdir -p meta
          echo "${{ github.event.pull_request.number }}" > meta/PR.txt
          echo "${{ github.event.pull_request.title }}" > meta/title.txt
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > meta/diff.txt

      - uses: actions/upload-artifact@v4
        with:
          name: pr-ai-metadata
          path: meta/
