name: Build and Push Nightly Docker Image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  packages: write
  statuses: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/s-pdf:${{ github.sha }}

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe
          name: Stirling-PDF${{ matrix.file_suffix }}.exe
          overwrite: true
          retention-days: 1
          if-no-files-found: error

      - name: Post Comment with Docker Image Link
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Docker Image is available: ghcr.io/${{ github.repository }}/s-pdf:${{ github.sha }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post Comment with Artifacts Link
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Download the Docker image artifact here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
