name: Check File in PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 20 # Um die Historie für PR-Branch zu erhalten

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch # Pfad zum Checkout des main-Branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Die Python-Version, die du benötigst

      - run: git diff --name-only origin/main...HEAD

      - name: Determine if reference file is from PR branch
        id: determine-file
        run: |
          git fetch origin
          echo "Fetching changes..."
          echo "Changed files:"
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q '^src/main/resources/messages_en_GB.properties$'; then
              echo "REFERENCE_FILE=src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          else
              echo "REFERENCE_FILE=main-branch/src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          fi

      - name: Run Python script to check file
        run: |
          python .github/scripts/check_language_files.py --reference-file ${{ env.REFERENCE_FILE }}
