name: Check Properties Files in PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: pr-branch
          fetch-depth: 0

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Fetch PR changed files
        id: fetch-pr-changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching PR changed files..."
          cd pr-branch
          gh pr view ${{ github.event.pull_request.number }} --json files -q ".files[].path" > ../changed_files.txt
          cd ..
          BRANCH_PATH="pr-branch"
          CHANGED_FILES=$(cat changed_files.txt | sed "s|^|$BRANCH_PATH/|" | tr '\n' '\x1e') # Use a non-printable character as delimiter
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV
          echo "Changed files: ${CHANGED_FILES}"

      - name: Determine reference file
        id: determine-file
        run: |
          echo "Determining reference file..."
          if echo "${{ env.CHANGED_FILES }}" | tr '\x1e' '\n' | grep -q 'src/main/resources/messages_en_GB.properties'; then
              echo "REFERENCE_FILE=pr-branch/src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          else
              echo "REFERENCE_FILE=main-branch/src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          fi
          echo "REFERENCE_FILE=${{ env.REFERENCE_FILE }}"

      - name: Show REFERENCE_FILE
        run: echo "Reference file is set to ${{ env.REFERENCE_FILE }}"

      - name: Run Python script to check files
        run: |
          python main-branch/.github/scripts/check_language_files.py --reference-file ${{ env.REFERENCE_FILE }} --files ${{ env.CHANGED_FILES }}
