name: Check File in PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Um die Historie für PR-Branch zu erhalten

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch  # Pfad zum Checkout des main-Branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Die Python-Version, die du benötigst

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installiere Abhängigkeiten, falls vorhanden

      - name: Run Python script to check file
        run: |
          python .github/scripts/check_language_files.py  # Führe dein Python-Skript aus
        env:
          REFERENCE_FILE: main-branch/src/main/resources/messages_en_GB.properties
