name: Check File in PR

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-branch
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Fetch and show branches
        run: |
          echo "Fetching changes..."
          git fetch origin
          echo "Current branch:"
          git branch --show-current
          echo "Remote branches:"
          git branch -r
          echo "Comparing changes..."
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "$CHANGED_FILES"

      - name: Determine if reference file is from PR branch
        id: determine-file
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | awk '/^src\/main\/resources\/messages_en_GB.properties$/ {found=1} END {exit !found}'; then
              echo "REFERENCE_FILE=src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          else
              echo "REFERENCE_FILE=main-branch/src/main/resources/messages_en_GB.properties" >> $GITHUB_ENV
          fi

      - name: Show REFERENCE_FILE
        run: echo "Reference file is set to ${{ env.REFERENCE_FILE }}"

      - name: Run Python script to check file
        run: |
          python .github/scripts/check_language_files.py --reference-file ${{ env.REFERENCE_FILE }}
