name: Test Installers Build

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  read_versions:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionNumber.outputs.versionNumber }}
      versionMac: ${{ steps.versionNumberMac.outputs.versionNumberMac }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Get version number
      - name: Get version number
        id: versionNumber
        run: |
          VERSION=$(grep "^version =" build.gradle | awk -F'"' '{print $2}')
          echo "versionNumber=$VERSION" >> $GITHUB_OUTPUT

      - name: Get version number mac
        id: versionNumberMac
        run: |
          # Extrahiere die Version aus der build.gradle-Datei
          VERSION=$(grep "^version =" build.gradle | awk -F'"' '{print $2}')

          # Hole das aktuelle Jahr
          CURRENT_YEAR=$(date +'%Y')

          # Zerlege die Version in ihre Teile
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"

          # Setze die neue Version zusammen
          MAC_VERSION="$CURRENT_YEAR.${VERSION_PARTS[1]:-0}.${VERSION_PARTS[2]:-0}"

          # Schreibe die macOS-Version in den GitHub-Output
          echo "versionNumberMac=$MAC_VERSION" >> $GITHUB_OUTPUT

  build-installers:
    needs: read_versions
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            ext: exe
          # - os: macos-latest
          #   platform: mac
          #   ext: dmg
          - os: ubuntu-latest
            platform: linux
            ext: deb
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: "21"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          gradle-version: 8.12

      # Install Windows dependencies
      - name: Install WiX Toolset
        if: matrix.os == 'windows-latest'
        run: |
          curl -L -o wix.exe https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe
          .\wix.exe /install /quiet

      # Install Linux dependencies
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot rpm

      # # Build installer
      - name: Build Installer
        run: ./gradlew build jpackage -x test --info
        env:
          DOCKER_ENABLE_SECURITY: false
          STIRLING_PDF_DESKTOP_UI: true

      # Rename and collect artifacts based on OS
      - name: Prepare artifacts
        id: prepare
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "build/jpackage/Stirling-PDF-${{ needs.read_versions.outputs.version }}.exe" "Stirling-PDF-${{ matrix.platform }}-installer.${{ matrix.ext }}"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            mv "build/jpackage/Stirling-PDF-${{ steps.versionNumberMac.outputs.versionNumberMac }}.dmg" "Stirling-PDF-${{ needs.read_versions.outputs.version }}-${{ matrix.platform }}.${{ matrix.ext }}"
          else
            mv "build/jpackage/stirling-pdf_${{ needs.read_versions.outputs.version }}-1_amd64.deb" "Stirling-PDF-${{ needs.read_versions.outputs.version }}-${{ matrix.platform }}.${{ matrix.ext }}"
          fi

      # # Upload installer as artifact for testing
      # - name: Upload Installer Artifact
      #   uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      #   with:
      #     name: Stirling-PDF-${{ matrix.platform }}-installer.${{ matrix.ext }}
      #     path: Stirling-PDF-${{ matrix.platform }}-installer.${{ matrix.ext }}
      #     retention-days: 1
      #     if-no-files-found: error

      # - name: Upload binaries to release
      #   uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
      #   with:
      #     files: ./Stirling-PDF-${{ matrix.platform }}-installer.${{ matrix.ext }}
