name: 'PR Title Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  issues:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR Title Verify
        uses: Ludy87/action/pr-issues-title-check@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues_pattern: '^(fix|feat|chore|docs|style|refactor|perf|test|\\[Feature Request\\]): (?:\w+\b\W*){3,8}$'
          issues_pattern_flags: gmi
