name: Build and Save PyMuPDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libclang-dev

      - name: Create directory for artifacts
        run: mkdir -p $HOME/pymupdf

      - name: Build PyMuPDF
        run: |
          pip install --break-system-packages --no-cache-dir libclang
          wget https://github.com/pymupdf/PyMuPDF/archive/refs/tags/1.24.9.tar.gz
          tar -xvf 1.24.9.tar.gz -C $HOME/pymupdf
          cd $HOME/pymupdf/PyMuPDF-1.24.9
          PYMUPDF_SETUP_MUPDF_TESSERACT=0 python3 setup.py bdist_wheel
          cd .. && rm -rf PyMuPDF-1.24.9 1.24.9.tar.gz

      - name: List files in dist directory
        run: ls -la $HOME/pymupdf/PyMuPDF-1.24.9/dist

      - name: Upload PyMuPDF build results
        uses: actions/upload-artifact@v4
        with:
          name: pymupdf-build
          path: $HOME/pymupdf/PyMuPDF-1.24.9/dist
          if-no-files-found: warn
