name: Build and Save PyMuPDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libclang-dev

      - name: Install Python packages
        run: |
          pip install --break-system-packages --no-cache-dir setuptools wheel libclang

      - name: Create directory for artifacts
        run: mkdir -p ${{ github.workspace }}/pymupdf

      - name: Build PyMuPDF
        run: |
          wget https://github.com/pymupdf/PyMuPDF/archive/refs/tags/1.24.9.tar.gz
          tar -xvf 1.24.9.tar.gz -C ${{ github.workspace }}/pymupdf
          cd ${{ github.workspace }}/pymupdf/PyMuPDF-1.24.9
          PYMUPDF_SETUP_MUPDF_TESSERACT=0 python3 setup.py bdist_wheel
          ls -la dist  # Überprüfe, ob das Wheel im dist-Verzeichnis vorhanden ist
          cd .. && rm -rf PyMuPDF-1.24.9 1.24.9.tar.gz

      # - name: List files in ${{ github.workspace }}/pymupdf
      #   run: ls -la ${{ github.workspace }}/pymupdf/PyMuPDF-1.24.9/dist

      # - name: Upload PyMuPDF build results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pymupdf-build
      #     path: ${{ github.workspace }}/pymupdf/PyMuPDF-1.24.9/dist/*.whl
      #     if-no-files-found: warn
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update files
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          signoff: true
          branch: pymupdf
          # base: main
          title: "🔨 Wheel <github-actions[bot]>"
          body: |
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
          delete-branch: true
