name: Check PyMuPDF Version

on:
  push:
    paths:
      - '.pymupdf'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read current version
        id: read_version
        run: |
          # Read the version from .pymupdf
          current_version=$(cat .pymupdf | tail -n +1 | head -n 1)
          echo "Current version: $current_version"
          echo "version=$current_version" >> $GITHUB_OUTPUT
