name: Build and Save PyMuPDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libclang-dev

      - name: Create directory for artifacts
        run: mkdir -p $HOME/pymupdf

      - name: Build PyMuPDF
        run: |
          pip install --break-system-packages --no-cache-dir libclang
          wget https://github.com/pymupdf/PyMuPDF/archive/refs/tags/1.24.9.tar.gz
          tar -xvf 1.24.9.tar.gz -C $HOME/pymupdf
          cd $HOME/pymupdf/PyMuPDF-1.24.9
          PYMUPDF_SETUP_MUPDF_TESSERACT=0 python3 setup.py install
          pip show pymupdf  # Überprüfe, ob PyMuPDF installiert ist
          cd .. && rm -rf PyMuPDF-1.24.9 1.24.9.tar.gz
      - name: Check installed PyMuPDF location
        run: |
          python3 -c "import pymupdf; print(pymupdf.__file__)"

      - name: List files in $HOME/pymupdf
        run: ls -la /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/pymupdf

      - name: Upload PyMuPDF build results
        uses: actions/upload-artifact@v4
        with:
          name: pymupdf-build
          path: /tmp/pymupdf
          if-no-files-found: warn
