name: Python Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel  # Install necessary build tools

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist/*.tar.gz
          dist/*.whl

    - name: Test the package
      run: |
        pip install dist/*.whl  # Install the built package

    - name: Set up git config
      run: |
        git config --global user.email "GitHub Action <action@github.com>"
        git config --global user.name "GitHub Action <action@github.com>"

    - name: Run git add
      run: |
        git add .
        git diff --staged --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV

    - name: Create Pull Request
      id: cpr
      if: env.CHANGES_DETECTED == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update Build MuPDF"
        committer: GitHub Action <action@github.com>
        author: GitHub Action <action@github.com>
        signoff: true
        branch: build-mupdf-js
        title: "Update Build MuPDF"
        body: |
          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: licenses
        draft: false
        delete-branch: true
