name: Release Artifacts

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        enable_security: [true, false]
        include:
          - enable_security: true
            file_suffix: "-with-login"
          - enable_security: false
            file_suffix: ""
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: "17"
          distribution: "temurin"

      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          gradle-version: 8.7

      - name: Generate jar (With Security=${{ matrix.enable_security }})
        run: ./gradlew clean createExe
        env:
          DOCKER_ENABLE_SECURITY: ${{ matrix.enable_security }}
          STIRLING_PDF_DESKTOP_UI: false

      - name: Get version number
        id: versionNumber
        run: echo "versionNumber=$(./gradlew printVersion --quiet | tail -1)" >> $GITHUB_OUTPUT

      - name: Rename binaries
        run: |
          cp ./build/launch4j/Stirling-PDF.exe ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe
          cp ./build/libs/Stirling-PDF-${{ steps.versionNumber.outputs.versionNumber }}.jar ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar

      # - name: Upload Assets
      #   id: upload-assets
      #   uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      #   with:
      #     name: "release-artifacts"
      #     path: |
      #       ./build/launch4j/Stirling-PDF-Server${{ matrix.file_suffix }}.exe
      #       ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign JAR with Cosign OIDC
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob \
            --yes \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar \
            > ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar.sig

      - name: Sign EXE with Cosign OIDC
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign-blob \
            --yes \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe \
            > ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe.sig

      - name: Generate Attestations for JAR
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign attest-blob \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            --predicate predicate.json \
            ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar \
            > ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar.attestation.jsonl

      - name: Generate Attestations for EXE
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign attest-blob \
            --oidc-client-id sigstore \
            --oidc-issuer https://token.actions.githubusercontent.com \
            --predicate predicate.json \
            ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe \
            > ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe.attestation.jsonl


      # - name: Upload binaries and signatures to release
      #   uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
      #   with:
      #     tag_name: v${{ steps.versionNumber.outputs.versionNumber }}
      #     files: |
      #       ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar
      #       ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar.sig
      #       ./build/libs/Stirling-PDF${{ matrix.file_suffix }}.jar.attestation.jsonl
      #       ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe
      #       ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe.sig
      #       ./build/launch4j/Stirling-PDF${{ matrix.file_suffix }}.exe.attestation.jsonl
