name: A Secure Check Properties

on:
  workflow_dispatch:
    inputs:
      files:
        description: "List of changed files"
        required: true
      actor:
        description: "User who opened the PR"
        required: true
      ref_file:
        description: "Reference file to use"
        required: true

jobs:
  check-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Log inputs
        run: |
          echo "Changed files: ${{ github.event.inputs.files }}"
          echo "Actor: ${{ github.event.inputs.actor }}"
          echo "Reference file: ${{ github.event.inputs.ref_file }}"

      - name: Run Python script
        run: |
          echo "Running Python script to check files..."
          python main/.github/scripts/check_language_properties.py \
            --actor ${{ github.event.inputs.actor }} \
            --reference-file "${{ github.event.inputs.ref_file }}" \
            --branch "" \
            --files "${{ github.event.inputs.files }}" > result.txt || true
