name: Compare Properties Files

on:
  pull_request:
    branches:
      - main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Get changed files
        id: changed_files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only origin/main)" >> $GITHUB_ENV

      - name: Run comparison script
        run: |
          changed_files=$(echo $CHANGED_FILES | tr ' ' '\n' | grep '^languages/messages_.*\.properties$')
          if [ -n "$changed_files" ]; then
            python compare_properties.py $changed_files
          fi

      - name: Create PR comment
        if: success() && steps.changed_files.outputs.CHANGED_FILES
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: comparison_result.txt
